### ISSUE TITLE
Error When Running kraken.py

### ISSUE THREAD

**Issue by jrede** [AbateLab/SiC-seq#3]
Hi @bdemaree 

I was hoping you could help me solve this error. The kraken database I used only comprises only Alteromonas genomes, and the sqlite database only contains SRR5208456. Thank you for any help!

command used:

```
python2 kraken.py --SE \
sicseq_456-ACE-50barCutoff.db 
```

Error:

Creating table for Kraken data...
Table kraken set up successfully.
6561396 sequences (836.53 Mbp) processed in 34.970s (11257.8 Kseq/m, 1435.28 Mbp/m).
  42099 sequences classified (0.64%)
  6519297 sequences unclassified (99.36%)
Traceback (most recent call last):
  File "kraken.py", line 289, in <module>
    kraken()    # Run Kraken and insert data into sqlite db
  File "kraken.py", line 218, in kraken
    (tableK, domain, phylum, Class, order, family, genus, species, barcode, barID))
sqlite3.OperationalError: no such table: kraken

**Comment by jrede** [comment]
The issue must have been in how I made the database. I downloaded the 8 gig mini-kraken database to test and it completed, however, no reads were added to the database! This shouldn't be correct, right? Because the default setting the script is to use mini-kraken.
